### PR TITLE
fix: Add types

### PR DESCRIPTION
**Pull request by baseplate-admin**
Closes : 
* https://github.com/markedjs/marked-xhtml/issues/37

### CODE REVIEW

**Review by UziTech — CHANGES_REQUESTED** [review]
Loks like you are missing the types test file like https://github.com/markedjs/marked-mangle/blob/main/spec/index.test-d.ts

**Comment by baseplate-admin** [comment]
Yep I was actively working on this :P 

Sorry for the noise

**Comment by baseplate-admin** [comment]
@UziTech Checks are green.

**Review by UziTech — APPROVED** [review]
No problem. Thanks for all the PRs! :100:

**Pull request merged**
